from llm.client import call_llm
from llm.prompts import (
    CREDIBILITY_RULES,
    INDUSTRY_ALPHA_SYSTEM,
    SINGLE_ETF_ANALYSIS_PROMPT,
    UNIVERSE_RANKING_PROMPT,
    MACRO_POSITIONING_PROMPT,
    CONSENSUS_DIAGNOSIS_PROMPT,
    VARIANT_PERCEPTION_PROMPT,
    ALLOCATION_DECISION_PROMPT,
)

__all__ = [
    "call_llm",
    "CREDIBILITY_RULES",
    "INDUSTRY_ALPHA_SYSTEM",
    "SINGLE_ETF_ANALYSIS_PROMPT",
    "UNIVERSE_RANKING_PROMPT",
    "MACRO_POSITIONING_PROMPT",
    "CONSENSUS_DIAGNOSIS_PROMPT",
    "VARIANT_PERCEPTION_PROMPT",
    "ALLOCATION_DECISION_PROMPT",
]
